# Base image 
FROM rocker/geospatial:4.1

# install the linux libraries needed for plumber
RUN apt-get update -qq && apt-get install -y \
  libssl-dev \
  libcurl4-gnutls-dev

## copy files
COPY install_packages.R /install_packages.R

## install R-packages
RUN Rscript /install_packages.R

EXPOSE 8787
