FROM rstudio_dev:v1.0.0

## install R-packages
RUN Rscript /install_packages.R

# Open port 80 to traffic
EXPOSE 8000

# Create directories
RUN mkdir -p /data
RUN mkdir -p /reports

# Change working directory
WORKDIR /home/rstudio

# Clone git repo of the product
RUN git clone --depth 1 -b v1.0.3 https://github.com/mark-me/poc_tailored_product_a.git

# Make bash script that runs the R script
RUN printf "#!/bin/bash\n \
cd poc_tailored_product_a\n \
Rscript main.R" > run.sh
RUN chmod +x run.sh

# when the container starts, start the main.R script
ENTRYPOINT ["./run.sh"]
